<link ng-href="{{theme_url}}/styles/bootstrap.min.css?{{g.ver}}"
      rel="stylesheet">
<link ng-href="{{theme_url}}/styles/responsive.css?{{g.ver}}"
      rel="stylesheet">
<link ng-href="{{theme_url}}/styles/style.css?{{g.ver}}"
      rel="stylesheet" >
<link ng-href="{{theme_url}}/styles/touch-touch.css?{{g.ver}}"
      rel="stylesheet">
<link ng-href="{{theme_url}}/styles/kwicks-slider.css?{{g.ver}}"
      rel="stylesheet">
<link href='{{theme_url}}/fonts/opensans/opensans.css?{{g.ver}}'
      rel='stylesheet'>
<style ng-bind="theme_meta.styles"></style>